/* Database schema to keep the structure of entire database. */

create table animals(   
id int generated always as identity,
name varchar NOT NULL,
date_of_birth date NOT NULL,
escape_attempts int,
neutered boolean, 
weight_kg decimal,
PRIMARY KEY (id)
);

ALTER TABLE animals ADD species varchar;

/* Project part 3 */
CREATE TABLE owners (
  id int generated by default as identity,
  full_name varchar,
  age smallint,
  PRIMARY KEY (id)
);

CREATE TABLE species (
  id int generated by default as identity,
  name varchar,
  PRIMARY KEY (id)
);

ALTER TABLE animals ALTER COLUMN id SET generated by default;
ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id int references species(id);
ALTER TABLE animals ADD COLUMN owner_id int references owners(id);


/* Project part 4 */
CREATE TABLE vets (
  id int generated by default as identity,
  name varchar,
  age smallint,
  date_of_graduation date,
  PRIMARY KEY(id)
);

CREATE TABLE specializations (
  vet_id int references vets(id),
  species_id int references species(id),
  PRIMARY KEY(vet_id, species_id)
);

CREATE TABLE visits (
  animal_id int references animals(id),
  vet_id int references vets(id),
  date_of_visit date,
  PRIMARY KEY (animal_id, vet_id, date_of_visit)
);

