/* Database schema to keep the structure of entire database. */

create table animals(   
id int generated always as identity,
name varchar NOT NULL,
date_of_birth date NOT NULL,
escape_attempts int,
neutered boolean, 
weight_kg decimal,
PRIMARY KEY (id)
);

ALTER TABLE animals ADD species varchar;

/* Project part 3 */
CREATE TABLE owners (
  id int generated by default as identity,
  full_name varchar,
  age smallint
);

CREATE TABLE species (
  id int generated by default as identity,
  name varchar
);

ALTER TABLE animals SET id int generated by default as identity;
ALTER TABLE animals DROP species;
ALTER TABLE animals ADD species_id references species(id);
ALTER TABLE animals ADD owner_id references owners(id);
