CREATE TABLE patients (
  id int generated by default as identity,
  name varchar not null,
  date_of_birth date not null,
  PRIMARY KEY (id)
);

CREATE TABLE medical_histories (
  id int generated by default as identity,
  admitted_at timestamp NOT NULL,
  patient_id int not null references patients(id),
  status varchar not null,
  PRIMARY KEY(id)
);

