CREATE TABLE patients (
  id int generated by default as identity,
  name varchar not null,
  date_of_birth date not null,
  PRIMARY KEY (id)
);

CREATE TABLE medical_histories (
  id int generated by default as identity,
  admitted_at timestamp NOT NULL,
  patient_id int not null references patients(id),
  status varchar not null,
  PRIMARY KEY(id)
);

CREATE TABLE invoices (
  id int generated by default as identity,
  total_amount decimal not null,
  generated_at timestamp not null,
  payed_at timestamp not null,
  medical_history_id int not null references medical_histories(id),
  PRIMARY KEY (id)
);

CREATE TABLE treatments (
  id int generated by default as identity,
  type varchar not null,
  name varchar not null,
  PRIMARY KEY (id)
);

CREATE TABLE invoice_items (
  id int generated by default as identity,
  unit_price decimal not null,
  quantity int not null,
  total_price decimal not null,
  invoice_id int not null references invoices(id),
  treatment_id int not null references treatments(id),
  PRIMARY KEY(id)
);

CREATE TABLE medical_histories_treaments (
  medical_history_id int not null references medical_histories(id),
  treatment_id int not null references treatments(id),
  PRIMARY KEY (medical_history_id, treatment_id)
);

CREATE INDEX patient_id_index ON medical_histories(patient_id ASC);
CREATE INDEX medical_history_id_index ON invoices(medical_history_id ASC);
CREATE INDEX invoice_treatment_index ON invoice_items(invoice_id ASC, treatment_id ASC);
CREATE INDEX medical_histories_treaments_index ON medical_histories_treaments(medical_history_id ASC, treatment_id ASC);
